name: Pulumi Deploy and Destroy

on:
  push:
    branches:
      - master
      - destroy

  workflow_dispatch:

jobs:
  pulumi-deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Pulumi
        run: curl -fsSL https://get.pulumi.com | sh

      - name: Add Pulumi to PATH
        run: echo "$HOME/.pulumi/bin" >> $GITHUB_PATH

      - name: Install project dependencies
        run: yarn install
        working-directory: packages/pulumi

      - name: Build Frontend
        run: yarn build:frontend

      - name: Build Backend
        run: yarn build:backend

      - name: Login to Pulumi
        run: pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Set up AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Zip Lambda code
        run: yarn zip:lambda
        working-directory: ${{ github.workspace }}

      - name: Ensure Pulumi stack exists
        run: pulumi stack select prod --create
        working-directory: packages/pulumi

      - name: Set AWS region
        run: pulumi config set aws:region us-east-1
        working-directory: packages/pulumi

      - name: Run Pulumi preview
        run: pulumi preview --stack prod
        working-directory: packages/pulumi

      - name: Run Pulumi up
        run: pulumi up --yes --stack prod
        working-directory: packages/pulumi

  pulumi-destroy:
    if: github.ref == 'refs/heads/destroy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Pulumi
        run: curl -fsSL https://get.pulumi.com | sh

      - name: Add Pulumi to PATH
        run: echo "$HOME/.pulumi/bin" >> $GITHUB_PATH

      - name: Install project dependencies
        run: yarn install
        working-directory: packages/pulumi

      - name: Login to Pulumi
        run: pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Set up AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Ensure Pulumi stack exists
        run: pulumi stack select prod --create
        working-directory: packages/pulumi

      - name: Set AWS region
        run: pulumi config set aws:region us-west-2
        working-directory: packages/pulumi

      - name: Run Pulumi destroy
        run: pulumi destroy --yes --stack prod
        working-directory: packages/pulumi
